import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CategoriasService {

  /* ========== Categorías ========== */
  private categorias = [
  
    {nombre: 'Alquiler p/ eventos',
      areas: [
        'Arreglos florales',
        'Baby shower',
        'Bautismos',
        'Barras p/ Eventos', // Nueva área
        'Bodas',
        'Cumpleaños',
        'Decoración de eventos', // Nueva área
        'Juegos',
        'Mobiliarios'
      ]
    },

    {nombre: 'Asociaciones y organizaciones',
      areas: [
        'Asociaciones', // Movido desde Servicios Públicos y Sociales
        'Consejo municipal', // Nueva área
        'Corredores inmobiliarios', // Nueva área
        'Cámara de comercio', // Nueva área
        'Federaciones',
        'Fundaciones',
        'ONG',
        'INTA', // Nueva área
        'Sindicatos',
        'Partidos políticos', // Nueva área
        'Sindicatos', // Nueva área
      ],
    },
  
    {nombre: 'Armería',
        
      areas: [
        'Accesorios para armas',
        'Armas',
        'Artículos de arquería',
        'Artículos de pesca',
        'Cuchillos tácticos',
        'Gestionar tramites',
        'Local',
        'Municiones',
      ],
    },
  
    {nombre: 'Bancos', 
      areas:[
        'Denominación',
        'Red de cajeros automáticos'
      ]
    },
  
    {nombre: 'Casas de cambio de divisas',
      
      areas: [
          'Asesoramiento',
          'Cambio de divisas',
          'Compra y venta',
          'Transferencia internacional',
      ],
    },

    {nombre: 'Comercio',
        
      areas: [
        'Afilados',
        'Alimentos congelados',
        'Alimentos gourmet',
        'Alimentos orgánicos',
        'Almacén',
        'Antigüedades',
        'Arte', // Movido aquí
        'Artesanías',
        'Autoservicio',
        'Bazar',
        'Bicicletas',
        'Bricolaje',
        'Calzado',
        'Camping',
        'Carnicería',
        'Catering', // Nueva área
        'Chocolatería',
        'Comida para llevar',
        'Comida rápida',
        'Comida sin gluten',
        'Cosméticos',
        'Deportes',
        'Distribuidoras',
        'Dulces',
        'Electrodomésticos',
        'Electrónica',
        'Envases',
        'Ferretería',
        'Fiambrerías', // Nueva área
        'Florería',
        'Fotocopias',
        'Fotografía',
        'Frutería',
        'Heladerías',
        'Herborerías y dietéticas',
        'Informática',
        'Inmuebles',
        'Insumos para el armado de bijouterie',
        'Jardinería',
        'Joyerías', // Nueva área
        'Juguetes',
        'Lanas e hilados',
        'Lavadero de autos', // Nueva área
        'Lavandería', // Nueva área
        'Librería',
        'Mascotas',
        'Mercado',
        'Mercerías',
        'Mini market',
        'Mini mercado',
        'Moda intervenida',
        'Muebles',
        'Música',
        'Óptica',
        'Panaderías',
        'Pañalerías',
        'Perfumerías',
        'Pescadería',
        'Pinturería', // Nueva área
        'Productos naturales',
        'Puestos de diarios y revistas',
        'Regalos',
        'Repostería',
        'Ropa',
        'Santerías',
        'Segunda mano',
        'Servicios de limpieza',
        'Sex shop',
        'Supermercado',
        'Té y café',
        'Verdulería',
        'Vinos y licores',
        'Viveros', // Nueva área
      ],
    },

    {nombre: 'Construcción',
      areas: [
        'Construcción de viviendas',
        'Cristales y vidrios',
        'Materiales para la construcción',
        'Aberturas', // Nueva área
      ],
    },
    
    {nombre: 'Deporte',
      
      areas: [
        'Atletismo',
        'Baloncesto',
        'Béisbol',
        'Boxeo',
        'Ciclismo',
        'Deportes acuáticos',
        'Deportes de aventura',
        'Deportes de combate',
        'Deportes de invierno',
        'Deportes de equipo',
        'Deportes de motor',
        'Deportes extremos',
        'Deportes individuales',
        'Deportes náuticos',
        'Elementos para Deportes', // Nueva área
        'Equitación',
        'Esgrima',
        'Fútbol',
        'Gimnasio',
        'Golf',
        'Maratón',
        'Montañismo',
        'Natación',
        'Patinaje', // Repetida (ya está en Comercio)
        'Rugby',
        'Skateboarding',
        'Suplementos nutricionales',
        'Surf', // Repetida (ya está en Comercio)
        'Tenis',
        'Local de ventas', // Nueva área
        'Voley',
        'Yoga'
      ],
    },
    
    {nombre: 'Educación',
      
      areas: [
        'Academias de idiomas',
        'Academias de música',
        'Bibliotecas',
        'Centros de educación infantil',
        'Centros de educación primaria',
        'Centros de educación secundaria',
        'Centros de formación profesional',
        'Centros de idiomas',
        'Clases particulares',
        'Colegios',
        'Escuelas de arte',
        'Escuelas de cocina',
        'Escuelas de danza',
        'Escuelas de diseño',
        'Escuelas de fotografía',
        'Escuelas de informática',
        'Escuelas de negocios',
        'Escuelas de teatro',
        'Guarderías',
        'Instituciones de enseñanza superior',
        'Jardines de infancia',
        'Universidades',
      ],
    },
    
    {nombre: 'Entretenimiento',
      
      areas: [
        'Actividades al aire libre',
        'Animación infantil',
        'Arcades',
        'Bares de karaoke',
        'Boliche',
        'Bowling', 
        'Casino', // Nueva área
        'Cines',
        'Clubes nocturnos',
        'Clubes sociales',
        'Conciertos',
        'Discotecas',
        'Escape rooms',
        'Eventos deportivos',
        'Eventos musicales',
        'Fiestas temáticas',
        'Gimnasios de escalada', // Nueva área
        'Juegos de mesa',
        'Juegos mecánicos',
        'Karaoke',
        'Paintball',
        'Parques acuáticos',
        'Parques de diversiones',
        'Parques temáticos',
        'Salas de billar',
        'Salas de conciertos',
        'Salas de escape',
        'Salones de baile',
        'Salones de fiesta', // Nueva área
        'Teatros',
        'Zoológicos',
      ],
    },
    
    {nombre: 'Estética y Belleza',
      
      areas: [
        'Armonización',
        'Aromaterapia',
        'Auriculoterapia',
        'Bodi up',
        'Body health',
        'Botox',
        'Bronceado instantaneo',
        'Cabina solar',
        'Camuflaje de manchas',
        'Celulitis',
        'Constelacionies',
        'Criolifting facial',
        'Criolipolisis',
        'Crioradiofrecuencia',
        'Depilación definitiva',
        'Depilación masculina',
        'Depilación tradicional',
        'Dermapen con peptonas',
        'Dermapen con PRP',
        'Dermapen microneedling',
        'Dermaplaning',
        'Dermaplaning facial',
        'Dermaplaning y microneedling',
        'Dermaplaning y peptonas',
        'Dermaplaning y radiofrecuencia',
        'Drenaje linfático',
        'Esmalte permanente en pies',
        'Exfoliación espalda, piernas y pies',
        'Extensión de pestañas',
        'Eye lifting',
        'Face y body',
        'Fibrosis',
        'Flacidez',
        'Flores de bach',
        'Hifu 12D',
        'Hifu 9D',
        'Hifu intimo',
        'Hifu liposonix',
        'Hifu vaginal',
        'Hifu v-max',
        'Higiene facial profunda',
        'Hilos tensores',
        'Himfu reductor',
        'Hiperhidrosis con botox',
        'Laminado de Cejas',
        'Laser lumiia',
        'Laser soprano',
        'Lifting de Pestañas',
        'Limpieza Facial c/extracciones',
        'Liposonix 4D',
        'Liposonix gold 360',
        'Local',
        'Luz pulsada',
        'Manicuría',
        'Maquillaje artístico',
        'Maquillaje social',
        'Masaje drenante brasilero',
        'Masaje psicosensitivo',
        'Masaje reductor',
        'Masajes',
        'Masajes faciales',
        'Medicina ortomolecular',
        'Memoria celular',
        'Microglanding',
        'Ondas rusas',
        'Pecas tratamiento',
        'Peeling de ojeras y bolsas',
        'Peeling médico',
        'Pelling enzimático',
        'Pelling químico',
        'Peluquería',
        'Perfilado de cejas',
        'Plasma frío',
        'Plasma Pen',
        'Podología',
        'Presoterapia',
        'Promociones',
        'Radiofrecuencia',
        'Radiofrecuencia facial',
        'Recuperación de pestañas',
        'Reflexología podal',
        'Regalos',
        'Reiki',
        'Relleno de labios',
        'Retiros acrílicos/poligel/softgel',
        'Rinomodelación',
        'Roll Active',
        'Sorteos',
        'Spa',
        'Spa de pies',
        'Terapia Shiatsu',
        'Trat. Capilares',
        'Trat. Despigmentante',
        'Trat. Modelador',
        'Trat. Ocular',
        'Trat. Rejuvenecedor facial',
        'Ultracavitación',
        'Uñas esculpidas',
        'Velaslim',
        'Ventas',
      ],
    },

    {nombre: 'Finanzas y seguros',
      areas: [
        'Ahorro e inversión',
        'Agencia de lotería', // Movido aquí
        'Asesoramiento financiero',
        'Banca electrónica',
        'Bancos',
        'Cajas de ahorro',
        'Cajas de seguridad',
        'Cajas rurales',
        'Cartera de valores',
        'Cooperativas de crédito',
        'Crédito',
        'Inversiones',
        'Leasing',
        'Planes de pensiones',
        'Planes de previsión',
        'Préstamos',
        'Seguros',
        'Servicios financieros',
      ],
    },
    
    {nombre: 'Gastronomía',
      areas: [
        'Alimentos congelados',
        'Alimentos gourmet',
        'Alimentos orgánicos',
        'Asadores',
        'Bares',
        'Cafeterías',
        'Catering',
        'Cenadurías',
        'Chocolaterías',
        'Comida a domicilio',
        'Comida callejera',
        'Comida rápida',
        'Comida saludable',
        'Comida vegetariana',
        'Confiterías',
        'Delicatessen',
        'Empanaderías',
        'Fiambrerías', // Nueva área
        'Fruterías',
        'Heladerías',
        'Panaderías',
        'Pastelerías',
        'Pescaderías',
        'Pizzerías',
        'Postres y repostería',
        'Restaurantes',
        'Rotiserías', // Nueva área
        'Supermercados',
        'Taquerías',
        'Tiendas de alimentos',
        'Tiendas de bebidas',
        'Tiendas de café',
        'Tiendas de dulces',
        'Tiendas de vinos y licores',
        'Verdulerías',
      ],
    },
    
    {nombre: 'Hotelería y alojamiento',
        
      areas: [
        'Agencias de turismo',
        'AIRBNB',
        'Alquileres',
        'Apartamentos',
        'Asesoramiento',
        'Booking.com',
        'Boutique',
        'Cabañas',
        'Despegar.com',
        'Hoteles',
        'Hoteles.com',
        'Inter Patagonia',
        'Paquetes turísticos',
        'Planificación de viajes',
        'Plataformas',
        'Reservas',
        'SolBooking',
        'Tours guiados',
        'Trivago',
        'TurismoCity',
        'VRBO (ex Homeaway)',
      ],
    },

    {nombre: 'Industria y manufactura',
      areas: [
        'Biometrías', // Nueva área
        'Frigoríficos', // Nueva área
        'Herrerías', // Nueva área
        'Imprentas', // Nueva área
        'Madereras', // Nueva área
        'Maquinarias agrícolas', // Nueva área
        'Metalúrgica', // Nueva área
        'Neumática', // Nueva área
        'Salinera', // Nueva área
        'Venta de agroquímicos', // Nueva área
      ],
    },

    {nombre: 'Moda',
      
      areas: [
        'Accesorios',
        'Bisutería',
        'Calzado',
        'Complementos',
        'Confección a medida',
        'Confección de alta costura',
        'Confección de trajes de baño',
        'Confección de uniformes',
        'Confección infantil',
        'Confección masculina',
        'Confección unisex',
        'Cosméticos',
        'Disfraces',
        'General',
        'Lencería',
        'Moda deportiva',
        'Moda femenina',
        'Moda infantil',
        'Moda íntima',
        'Moda masculina',
        'Moda nupcial',
        'Moda para bebés',
        'Moda para embarazadas',
        'Moda para niños',
        'Moda sostenible',
        'Ropa de trabajo',
        'Ropa informal',
        'Ropa para adolescentes',
        'Ropa para adultos mayores',
        'Ropa para niños',
        'Ropa premamá',
        'Sombrerería',
        'Tallas grandes',
        'Uniformes escolares',
        'Vestuario teatral',
        'Zapatería',
      ],
    },

    {nombre: 'Oficios',
        
      areas: [
        'Albañilería',
        'Carpintería',
        'Cerrajería',
        'Electricistas',
        'Fontanería',
        'Jardinería',
        'Mecánicos',
        'Pintores',
        'Plomería',
        'Soldadores',
        'Técnicos',
        'Telecomunicaciones',
        'Transporte',
        'Vigilancia',
      ],
    },
    
    {nombre: 'Profesiones Liberales',
      areas: [
        'Abogados',
        'Agrónomos',
        'Arquitectos',
        'Artista plástico',
        'Consultores',
        'Corredores de Bienes inmuebles',
        'Decorador de interiores',
        'Diseñadores gráficos',
        'Economistas',
        'Escritores',
        'Fotógrafos',
        'Ingenieros',
        'Notarios',
        'Paisajistas',
        'Periodistas',
        'Traductores e intérpretes',
        'Wedding planner' // Nueva área
      ],
    },

    {nombre: 'Salud',
      
      areas: [
        'Alergista',
        'Anatomía patológica',
        'Anestesiología',
        'ART',
        'Banco de Sangre',
        'Biodecodificación',
        'Cardiología',
        'Centro de cirugía plástica y reparadora',
        'Centro oncológico',
        'Centros de meditación',
        'Centros de salud municipal',
        'Cirugía cardiovascular',
        'Cirugía general',
        'Cirugía maxilofacial',
        'Cirugía mini invasiva',
        'Cirugía oral',
        'Cirugía plástica',
        'Cirugía torácica',
        'Cirugía vascular periférica',
        'Clínica',
        'Clínica general',
        'Consultorio externo',
        'Deportología',
        'Dermatología',
        'Diabetología',
        'Diagnóstico por imagen',
        'Diálisis',
        'Electrofisiología',
        'Electromiografía',
        'Endocrinología',
        'Endocrinólogo',
        'Especialista en hombros y rodillas',
        'Estimulación temprana',
        'Farmacias',
        'Fisiatría',
        'Flebología',
        'Fonoaudiología',
        'Fototerapia',
        'Gastroenterología',
        'Gemoterapia',
        'Gerentología',
        'Hematología',
        'Hemodinamia',
        'Hepatología',
        'Hospital',
        'Inmunología',
        'Instituto diagnósticos',
        'Instituto radiología',
        'Kinesiología',
        'Laboratorio',
        'Lase en oftalmología',
        'Masología',
        'Medicina ayurveda',
        'Medicina laboral',
        'Medicina reproductiva',
        'Mesoterapia',
        'Nefrología',
        'Neumonología',
        'Neuro cirugía',
        'Neurología',
        'Neuroortopedía',
        'Nutrición',
        'Obstetricia',
        'Odontología',
        'Oftalmología',
        'Oncología',
        'Ortesis plantares',
        'Ortopedias',
        'Otorrinnolaringología',
        'PAMI dentro de los sanatorios',
        'Pediatría y meonatología',
        'Psicología',
        'Psicopedagogía',
        'Psiquiatría',
        'Quiropraxia',
        'Radioterápia oneológica',
        'Rehabilitación vestibular',
        'Reumatología',
        'Sanatorio',
        'Servicios de ambulancia', // Nueva área
        'Servicio de ortopedia y traumatología',
        'Terapias alternativas',
        'Terapias holísticas',
        'Traumatología',
        'Urología',
      ],
    },

    {nombre: 'Servicios de pagos y recaudación',
        
      areas: [
        'Pago Fácil',
        'Pre pagas',
        'Pronto Pago',
        'RapiPago',
        'Santa Fe Plus',
        'Seguros',
        'Western Unión',
      ],
    },
    
    {nombre: 'Servicios de reparación',
      
      areas: [
          'Automóviles',
          'Calzado',
          'Club de reparadores',
          'Dispositivos electrónicos',
          'Electrodomésticos',
          'Lavarropas',
          'Muebles',
          'Nebulizadores',
          'Ropa',
      ],
    },

    {nombre: 'Servicios Públicos y Sociales',
      areas: [
        'Administraciones públicas',
        'Agua potable',
        'Anses', // Nueva área
        'API',
        'Asociaciones', // Movido a Asociaciones y organizaciones
        'Ayuntamiento',
        'Bomberos',
        'Cámaras de comercio',
        'Cementerio',
        'Consulados',
        'Correos',
        'Delegaciones de gobierno',
        'Defensa al consumidor', // Nueva área
        'Defensoría del pueblo',
        'Embajadas',
        'Estaciones de servicio',
        'Guardia civil',
        'Ministerios',
        'Lideco (Ley 24240)', // Nueva área
        'Oficinas de empleo',
        'Oficinas de turismo',
        'Organismos autónomos',
        'Policía',
        'Protección civil',
        'Radio AM',
        'Radio FM',
        'Registro de automotor', // Nueva área
        'Registro de motos', // Nueva área
        'Secretaria de trabajo', // Nueva área
        'Servicios sociales',
        'TV local',
        'Coop. eléctrica', // Nueva área
        'Coop. obras sanitarias', // Nueva área
        'E.P.E', // Nueva área
        'Litoral gas', // Nueva área
      ]
    },

    {nombre: 'Servicios varios',
      areas: [
        'Consultoras de trabajos', // Nueva área
        'Descartables', // Nueva área
        'Estudio jurídico', // Nueva área
        'Equipamiento comercial', // Nueva área
        'Geriátricos', // Nueva área
        'Lavadero de autos', // Nueva área
        'Lavandería', // Nueva área
        'Modistas', // Nueva área
        'Obras sociales', // Nueva área
        'Péndulo Hebreo',
        'Péndulo Karnak',
        'Servicio de transporte', // Nueva área
        'Servicios fúnebres', // Nueva área
        'Servicios de cable e internet', // Nueva área
        'Tarot',
        'Teléfonos útiles',
        'Refrigeración y calefacción', // Nueva área
      ],
    },
      
    {nombre: 'Seguridad y protección',
      areas: [
        'Alarmas', // Nueva área
        'Servicios de vigilancia', // Nueva área
      ],
    },

    {nombre: 'Tecnología',
      
      areas: [
        'Accesorios',
        'Audio',
        'Cámaras',
        'Celulares y teléfonos',
        'Componentes de PC',
        'Componentes electrónicos',
        'Conectividad y redes',
        'Consolas',
        'Desarrollo de aplicaciones móviles',
        'Desarrollo de software',
        'Diseño gráfico',
        'Diseño web',
        'Gestión de proyectos de TI',
        'Hardware',
        'Hosting',
        'Impresiones',
        'Ingeniería de sistemas',
        'Inteligencia artificial',
        'Internet',
        'Mantenimiento de sistemas',
        'Mercado en línea de tecnología',
        'PC',
        'Realidad aumentada',
        'Realidad virtual',
        'Redes y comunicaciones',
        'Reparación de celulares',
        'Reparación de PC',
        'Reparación general',
        'Robótica',
        'Seguridad informática',
        'Servicio de cable e internet', // Nueva área
        'Soporte técnico',
        'Tecnologías de la información',
        'Testing de software',
        'Venta de productos tecnológicos',
        'Video',
        'Videojuegos',
        'Ventas',
      ],
    },

    {nombre: 'Transporte y alquiler',
      areas: [
        'Agencia', 
        'Alquiler de vehículos',
        'Alquileres quinta',
        'Comisiones',
        'Estaciones de servicio',
        'Estación de Ómnibus',
        'Taxis',
        'Transporte público',
        'Transportistas',
        'Servicios de ambulancia', // Nueva área
        'Serv. Cadetería',
      ],
    },
    // Agrega más categorías y áreas según necesites
  ];

  getCategorias() {
    return this.categorias;
  }

  getCategoriaAreas(categoriaNombre: string): string[] {
    const categoria = this.categorias.find((c) => c.nombre === categoriaNombre);
    return categoria ? categoria.areas : [];
  }
}