import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CategoriasService {

  /* ========== Categorías ========== */
  private categorias = [
    {nombre: 'Armería',
        
      areas: [
        'Accesorios para armas',
        'Armas',
        'Artículos de arquería',
        'Artículos de pesca',
        'Cuchillos tácticos',
        'Gestionar tramites',
        'Local',
        'Municiones',
      ],
    },
  
    {nombre: 'Bancos', 
      areas:[
        'Denominación',
        'Red de cajeros automáticos'
      ]
    },
  
    {nombre: 'Casas de cambio de divisas',
      
      areas: [
          'Asesoramiento',
          'Cambio de divisas',
          'Compra y venta',
          'Transferencia internacional',
      ],
    },

    {nombre: 'Comercio',
        
      areas: [
        'Alimentos congelados',
        'Alimentos gourmet',
        'Alimentos orgánicos',
        'Almacén',
        'Antigüedades',
        'Arte',
        'Artesanías',
        'Autoservicio',
        'Bazar',
        'Bicicletas',
        'Bricolaje',
        'Calzado',
        'Camping',
        'Carnicería',
        'Catering',
        'Chocolatería',
        'Comida para llevar',
        'Comida rápida',
        'Comida sin gluten',
        'Cosméticos',
        'Deportes',
        'Distribuidoras',
        'Dulces',
        'Electrodomésticos',
        'Electrónica',
        'Ferretería',
        'Florería',
        'Fotocopias',
        'Fotografía',
        'Frutería',
        'Heladerías',
        'Herborerías y dietéticas',
        'Informática',
        'Inmuebles',
        'Insumos para el armado de bijouterie',
        'Jardinería',
        'Juguetes',
        'Lanas e hilados',
        'Lavadero de autos',
        'Lavandería',
        'Librería',
        'Mascotas',
        'Mercado',
        'Mercerías',
        'Mini mercado',
        'Moda intervenida',
        'Muebles',
        'Música',
        'Óptica',
        'Panaderías',
        'Pañalerías',
        'Patinaje',
        'Perfumerías',
        'Pescadería',
        'Pinturería',
        'Productos naturales',
        'Puestos de diarios y revistas',
        'Regalos',
        'Repostería',
        'Ropa',
        'Santerías',
        'Segunda mano',
        'Servicios de limpieza',
        'Supermercado',
        'Surf',
        'Té y café',
        'Verdulería',
        'Vinos y licores',
      ],
    },
    
    {nombre: 'Deporte',
      
      areas: [
        'Atletismo',
        'Baloncesto',
        'Béisbol',
        'Boxeo',
        'Ciclismo',
        'Deportes acuáticos',
        'Deportes de aventura',
        'Deportes de combate',
        'Deportes de invierno',
        'Deportes de equipo',
        'Deportes de motor',
        'Deportes extremos',
        'Deportes individuales',
        'Deportes náuticos',
        'Equitación',
        'Esgrima',
        'Fútbol',
        'Gimnasio',
        'Golf',
        'Maratón',
        'Montañismo',
        'Natación',
        'Patinaje',
        'Rugby',
        'Skateboarding',
        'Surf',
        'Tenis',
        'Local de ventas',
        'Voleibol',
      ],
    },
    
    {nombre: 'Educación',
      
      areas: [
        'Academias de idiomas',
        'Academias de música',
        'Bibliotecas',
        'Centros de educación infantil',
        'Centros de educación primaria',
        'Centros de educación secundaria',
        'Centros de formación profesional',
        'Centros de idiomas',
        'Clases particulares',
        'Colegios',
        'Escuelas de arte',
        'Escuelas de cocina',
        'Escuelas de danza',
        'Escuelas de diseño',
        'Escuelas de fotografía',
        'Escuelas de informática',
        'Escuelas de negocios',
        'Escuelas de teatro',
        'Guarderías',
        'Instituciones de enseñanza superior',
        'Jardines de infancia',
        'Universidades',
      ],
    },
    
    {nombre: 'Entretenimiento',
      
      areas: [
        'Actividades al aire libre',
        'Animación infantil',
        'Arcades',
        'Bares de karaoke',
        'Bowling',
        'Cines',
        'Clubes nocturnos',
        'Conciertos',
        'Discotecas',
        'Escape rooms',
        'Eventos deportivos',
        'Eventos musicales',
        'Fiestas temáticas',
        'Gimnasios de escalada',
        'Juegos de mesa',
        'Juegos mecánicos',
        'Painball',
        'Parques acuáticos',
        'Parques de diversiones',
        'Parques temáticos',
        'Salas de billar',
        'Salas de conciertos',
        'Salas de escape',
        'Salones de baile',
        'Teatros',
        'Zoológicos',
      ],
    },
    
    {nombre: 'Estética y Belleza',
      
      areas: [
        'Armonización',
        'Aromaterapia',
        'Auriculoterapia',
        'Bodi up',
        'Body health',
        'Botox',
        'Bronceado instantaneo',
        'Cabina solar',
        'Camuflaje de manchas',
        'Celulitis',
        'Constelacionies',
        'Criolifting facial',
        'Criolipolisis',
        'Crioradiofrecuencia',
        'Depilación definitiva',
        'Depilación masculina',
        'Depilación tradicional',
        'Dermapen con peptonas',
        'Dermapen con PRP',
        'Dermapen microneedling',
        'Dermaplaning',
        'Dermaplaning facial',
        'Dermaplaning y microneedling',
        'Dermaplaning y peptonas',
        'Dermaplaning y radiofrecuencia',
        'Drenaje linfático',
        'Esmalte permanente en pies',
        'Exfoliación espalda, piernas y pies',
        'Extensión de pestañas',
        'Eye lifting',
        'Face y body',
        'Fibrosis',
        'Flacidez',
        'Flores de bach',
        'Hifu 12D',
        'Hifu 9D',
        'Hifu intimo',
        'Hifu liposonix',
        'Hifu vaginal',
        'Hifu v-max',
        'Higiene facial profunda',
        'Hilos tensores',
        'Himfu reductor',
        'Hiperhidrosis con botox',
        'Laminado de Cejas',
        'Laser lumiia',
        'Laser soprano',
        'Lifting de Pestañas',
        'Limpieza Facial c/extracciones',
        'Liposonix 4D',
        'Liposonix gold 360',
        'Local',
        'Luz pulsada',
        'Manicuría',
        'Masaje drenante brasilero',
        'Masaje psicosensitivo',
        'Masaje reductor',
        'Masajes',
        'Masajes faciales',
        'Medicina ortomolecular',
        'Microglanding',
        'Ondas rusas',
        'Pecas tratamiento',
        'Peeling de ojeras y bolsas',
        'Peeling médico',
        'Pelling enzimático',
        'Pelling químico',
        'Perfilado de cejas',
        'Plasma frío',
        'Plasma Pen',
        'Podología',
        'Presoterapia',
        'Promociones',
        'Radiofrecuencia',
        'Radiofrecuencia facial',
        'Recuperación de pestañas',
        'Reflexología podal',
        'Regalos',
        'Reiki',
        'Relleno de labios',
        'Retiros acrílicos/poligel/softgel',
        'Rinomodelación',
        'Roll Active',
        'Sorteos',
        'Spa',
        'Spa de pies',
        'Terapia Shiatsu',
        'Trat. Capilares',
        'Trat. Despigmentante',
        'Trat. Modelador',
        'Trat. Ocular',
        'Trat. Rejuvenecedor facial',
        'Ultracavitación',
        'Uñas esculpidas',
        'Velaslim',
        'Ventas',
      ],
    },
    
    {nombre: 'Hotelería y alojamiento',
        
      areas: [
        'Agencias de turismo',
        'AIRBNB',
        'Alquileres',
        'Apartamentos',
        'Asesoramiento',
        'Booking.com',
        'Boutique',
        'Cabañas',
        'Despegar.com',
        'Hoteles',
        'Hoteles.com',
        'Inter Patagonia',
        'Paquetes turísticos',
        'Planificación de viajes',
        'Plataformas',
        'Reservas',
        'SolBooking',
        'Tours guiados',
        'Trivago',
        'TurismoCity',
        'VRBO (ex Homeaway)',
      ],
    },

    {nombre: 'Moda',
      
      areas: [
        'Accesorios',
        'Bisutería',
        'Calzado',
        'Complementos',
        'Confección a medida',
        'Confección de alta costura',
        'Confección de trajes de baño',
        'Confección de uniformes',
        'Confección infantil',
        'Confección masculina',
        'Confección unisex',
        'Cosméticos',
        'Disfraces',
        'General',
        'Lencería',
        'Moda deportiva',
        'Moda femenina',
        'Moda infantil',
        'Moda íntima',
        'Moda masculina',
        'Moda nupcial',
        'Moda para bebés',
        'Moda para embarazadas',
        'Moda para niños',
        'Moda sostenible',
        'Ropa de trabajo',
        'Ropa informal',
        'Ropa para adolescentes',
        'Ropa para adultos mayores',
        'Ropa para niños',
        'Ropa premamá',
        'Sombrerería',
        'Tallas grandes',
        'Uniformes escolares',
        'Vestuario teatral',
        'Zapatería',
      ],
    },

    {nombre: 'Oficios',
        
      areas: [
        'Albañil',
        'Artista',
        'Carpintero',
        'Cerrajero',
        'Consultores',
        'Corredores de bienes inmuebles',
        'Decoración de eventos',
        'Decorador de interiores',
        'Diseñador gráfico',
        'Economista',
        'Electricista',
        'Escritores',
        'Fotógrafo',
        'Gasista',
        'Pintor',
        'Plomero',
        'Soldador',
        'Traductor',
        'Zinguería',
      ],
    },
    
    {nombre: 'Salud',
      
      areas: [
        'Alergista',
        'Anatomía patológica',
        'Anestesiología',
        'ART',
        'Banco de Sangre',
        'Cardiología',
        'Centro de cirugía plástica y reparadora',
        'Centro oncológico',
        'Centros de meditación',
        'Centros de salud municipal',
        'Cirugía cardiovascular',
        'Cirugía general',
        'Cirugía maxilofacial',
        'Cirugía mini invasiva',
        'Cirugía oral',
        'Cirugía plástica',
        'Cirugía torácica',
        'Cirugía vascular periférica',
        'Clínica',
        'Clínica general',
        'Consultorio externo',
        'Deportología',
        'Dermatología',
        'Diabetología',
        'Diagnóstico por imagen',
        'Diálisis',
        'Electrofisiología',
        'Electromiografía',
        'Endocrinología',
        'Endocrinólogo',
        'Especialista en hombros y rodillas',
        'Estimulación temprana',
        'Farmacias',
        'Fisiatría',
        'Flebología',
        'Fonoaudiología',
        'Fototerapia',
        'Gastroenterología',
        'Gerentología',
        'Hematología',
        'Hemodinamia',
        'Hepatología',
        'Hospital',
        'Inmunología',
        'Instituto diagnósticos',
        'Instituto radiología',
        'Kinesiología',
        'Laboratorio',
        'Lase en oftalmología',
        'Masología',
        'Medicina ayurveda',
        'Medicina laboral',
        'Medicina reproductiva',
        'Mesoterapia',
        'Nefrología',
        'Neumonología',
        'Neuro cirugía',
        'Neurología',
        'Neuroortopedía',
        'Nutrición',
        'Obstetricia',
        'Odontología',
        'Oftalmología',
        'Oncología',
        'Ortesis plantares',
        'Otorrinnolaringología',
        'PAMI dentro de los sanatorios',
        'Pediatría y meonatología',
        'Psicología',
        'Psicopedagogía',
        'Psiquiatría',
        'Quiropraxia',
        'Radioterápia oneológica',
        'Rehabilitación vestibular',
        'Reumatología',
        'Sanatorio',
        'Servicio de ortopedia y traumatología',
        'Terapias alternativas',
        'Terapias holísticas',
        'Traumatología',
        'Urología',
      ],
    },

    {nombre: 'Servicios de pagos y recaudación',
        
      areas: [
        'Pago Fácil',
        'Pronto Pago',
        'RapiPago',
        'Santa Fe Plus',
      ],
    },
    
    {nombre: 'Servicios de reparación',
      
      areas: [
          'Automóviles',
          'Calzado',
          'Club de reparadores',
          'Dispositivos electrónicos',
          'Electrodomésticos',
          'Lavarropas',
          'Muebles',
          'Nebulizadores',
          'Ropa',
      ],
    },

    {nombre: 'Tecnología',
      
      areas: [
        'Accesorios',
        'Audio',
        'Cámaras',
        'Celulares y teléfonos',
        'Componentes de PC',
        'Componentes electrónicos',
        'Conectividad y redes',
        'Consolas',
        'Desarrollo de aplicaciones móviles',
        'Desarrollo de software',
        'Diseño gráfico',
        'Diseño web',
        'Gestión de proyectos de TI',
        'Hardware',
        'Impresiones',
        'Ingeniería de sistemas',
        'Inteligencia artificial',
        'Mercado en línea de tecnología',
        'PC',
        'Realidad aumentada',
        'Realidad virtual',
        'Redes y comunicaciones',
        'Reparación de celulares',
        'Reparación de PC',
        'Reparación general',
        'Robótica',
        'Soporte técnico',
        'Tecnologías de la información',
        'Testing de software',
        'Venta de productos tecnológicos',
        'Video',
        'Videojuegos',
        'Ventas',
      ],
    },
    
    // Agrega más categorías y áreas según necesites
  ];

  getCategorias() {
    return this.categorias;
  }

  getCategoriaAreas(categoriaNombre: string): string[] {
    const categoria = this.categorias.find((c) => c.nombre === categoriaNombre);
    return categoria ? categoria.areas : [];
  }
}